name: Build and deploy static site to S3

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1         # <-- set to your bucket's region
  S3_BUCKET: your-bucket-name   # <-- set to your bucket name
  BUILD_DIR: dist               # <-- change to 'build' or '.next/out' etc.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify bucket
        run: aws s3 ls "s3://${{ env.S3_BUCKET }}"

      - name: Sync build output to S3
        run: |
          aws s3 sync "${{ env.BUILD_DIR }}/" "s3://${{ env.S3_BUCKET }}" \
            --delete --exact-timestamps
