name: Deploy to S3

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If your built site lives in / (plain static files), keep this.
      # If you build (React/Vite/etc.), add a build step and change `SOURCE_DIR` below.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          SOURCE_DIR: .
        run: |
          aws s3 sync "$SOURCE_DIR" "s3://$S3_BUCKET" \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md"

      # Optional: set correct cache headers for common assets
      - name: Set cache headers (optional)
        if: always()
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 cp s3://$S3_BUCKET/ s3://$S3_BUCKET/ \
            --recursive \
            --exclude "*" --include "*.css" --include "*.js" --include "*.png" --include "*.jpg" \
            --metadata-directive REPLACE \
            --cache-control "public,max-age=31536000,immutable" \
            --content-type ""

